/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalProj;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author connorbowley
 */
public class AllAircraftPanel extends javax.swing.JPanel {

    //private ArrayList<Aircraft> planes;
    
    finalProjMain main;
    /**
     * Creates new form AllAircraftPanel
     * @param main
     */
    public AllAircraftPanel(finalProjMain main) {
        initComponents();
        this.main = main;
    }
    
    public void addPlane (Aircraft plane) {
        //jList1.add
        listModel.addElement(plane.getName());
        //planes.add(plane);
    }
    
    public void removePlane (Aircraft plane) {
        //jList1.add
        for (int i = 0; i < listModel.getSize(); i++) {
            if (plane.getName().equals((String)listModel.get(i))) {
                listModel.remove(i);
                //planes.remove(plane);
            }
        }
    }
    
    public void updateSelected (String name) {
        for (int i = 0; i < listModel.size(); i++) {
            if (name.equals(listModel.getElementAt(i))) {
                jList1.setSelectedIndex(i);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aircraft Info");

        jList1.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        listModel = new DefaultListModel();
        jList1.setModel(listModel);
        jList1.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int selectedIndex = jList1.getSelectedIndex();
                ArrayList<Aircraft> planes = finalProjMain.getAircraftList();
                Aircraft plane = null;
                for (int i = 0; i < planes.size(); i++) {
                    if (planes.get(i).getName().equals(listModel.getElementAt(selectedIndex).toString())) {
                        plane = planes.get(i);
                        break;
                    }
                }
                finalProjMain.getCAP().updatePanel(plane);
            }
        });
        jScrollPane1.setViewportView(jList1);
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    public javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    public DefaultListModel listModel;
    // End of variables declaration//GEN-END:variables
}
